# Generated by Django 3.1.2 on 2020-11-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auction', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AddField(
            model_name='taskbid',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AddField(
            model_name='taskbid',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auction.task'),
        ),
        migrations.AddField(
            model_name='taskassigned',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AddField(
            model_name='taskassigned',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auction.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
    ]
